{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "39a9e597",
   "metadata": {},
   "outputs": [],
   "source": [
    "from tkinter import *\n",
    "import smtplib\n",
    "import email.message\n",
    "from tkinter import ttk, filedialog\n",
    "def btn_clicked():\n",
    "    try:\n",
    "        corpo_email = f\"\"\"<p>{entry_textbox.get('1.0', END)}</p>\"\"\"\n",
    "        msg = email.message.Message()\n",
    "        msg['Subject'] = 'REPORT CAPONE'\n",
    "        msg['From'] = 'reportcapone@gmail.com'\n",
    "        msg['To'] = 'reportcapone@gmail.com'\n",
    "        password = '************'\n",
    "        msg.add_header('Content-Type', 'text/html')\n",
    "        msg.set_payload(corpo_email)\n",
    "        s = smtplib.SMTP('smtp.gmail.com: 587')\n",
    "        s.starttls()\n",
    "        s.login(msg['From'], password)\n",
    "        s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))\n",
    "        messagebox.showinfo(message='Ticket enviado')\n",
    "    except:\n",
    "        messagebox.showerror(title='Erro de envio', message='Algo deu errado... Verifique sua conexão com a internet')\n",
    "        \n",
    "janela_gmail = Tk()\n",
    "janela_gmail.title('REPORT EMAIL')\n",
    "janela_gmail.geometry(\"422x257\")\n",
    "janela_gmail.configure(bg = \"#2a2a2a\")\n",
    "canvas = Canvas(\n",
    "    janela_gmail,\n",
    "    bg = \"#2a2a2a\",\n",
    "    height = 257,\n",
    "    width = 422,\n",
    "    bd = 0,\n",
    "    highlightthickness = 0,\n",
    "    relief = \"ridge\")\n",
    "canvas.place(x = 0, y = 0)\n",
    "\n",
    "entry0_img = PhotoImage(file = f\"img_textBox0gmail.png\")\n",
    "entry0_bg = canvas.create_image(\n",
    "    211.5, 166.5,\n",
    "    image = entry0_img)\n",
    "\n",
    "entry_textbox = Text(janela_gmail,\n",
    "    bd = 0,\n",
    "    bg = \"#ffffff\",\n",
    "    highlightthickness = 0)\n",
    "\n",
    "entry_textbox.place(\n",
    "    x = 40, y = 121,\n",
    "    width = 343,\n",
    "    height = 89)\n",
    "\n",
    "img0 = PhotoImage(file = f\"img0gmail.png\")\n",
    "botao_enviar_gmail = Button(janela_gmail,\n",
    "    image = img0,\n",
    "    borderwidth = 0,\n",
    "    highlightthickness = 0,\n",
    "    command = btn_clicked,\n",
    "    relief = \"flat\")\n",
    "\n",
    "botao_enviar_gmail.place(\n",
    "    x = 158, y = 220,\n",
    "    width = 106,\n",
    "    height = 31)\n",
    "\n",
    "background_img = PhotoImage(file = f\"bggmail.png\")\n",
    "background = canvas.create_image(\n",
    "    208.0, 61.5,\n",
    "    image=background_img)\n",
    "\n",
    "janela_gmail.resizable(False, False)\n",
    "janela_gmail.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e7a7af19",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
